/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_decard_lib_jnistruct_NativeLibrary */

#ifndef _Included_com_decard_lib_jnistruct_NativeLibrary
#define _Included_com_decard_lib_jnistruct_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_decard_lib_jnistruct_NativeLibrary
 * Method:    getDataFromNative
 * Signature: ()Lcom/decard/lib/jnistruct/data/DataBean;
 */
JNIEXPORT jobject JNICALL Java_com_decard_lib_jnistruct_NativeLibrary_getDataFromNative
  (JNIEnv *, jclass);

/*
 * Class:     com_decard_lib_jnistruct_NativeLibrary
 * Method:    transferDataToNative
 * Signature: (Lcom/decard/lib/jnistruct/data/DataBean;)V
 */
JNIEXPORT void JNICALL Java_com_decard_lib_jnistruct_NativeLibrary_transferDataToNative
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
